import jsPDF from "jspdf";
import * as XLSX from "xlsx";

interface ReportData {
  title: string;
  headers: string[];
  rows: (string | number)[][];
  generatedAt?: string;
}

function addHeader(doc: jsPDF, title: string) {
  // Header bar
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("LuxeStay ERP", 14, 12);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(title, 14, 20);

  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 210 - 14, 12, { align: "right" });
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 210 - 14, 20, { align: "right" });
}

function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const y = 290;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y - 4, 196, y - 4);

  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by LuxeStay ERP — Confidential", 14, y);
  doc.text(`Page ${pageNumber} of ${totalPages}`, 196, y, { align: "right" });
}

export function exportToPDF(data: ReportData): void {
  const doc = new jsPDF();

  addHeader(doc, data.title);

  // Table
  let y = 36;
  const cellPadding = 4;
  const pageWidth = 182;
  const colWidths = data.headers.map(() => pageWidth / data.headers.length);

  // Header row
  doc.setFillColor(38, 38, 38);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");

  let x = 14;
  data.headers.forEach((header, i) => {
    doc.rect(x, y, colWidths[i], 10, "F");
    doc.text(header, x + cellPadding, y + 7);
    x += colWidths[i];
  });

  y += 10;

  // Count pages for footer
  let pages = 1;

  // Data rows
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);

  data.rows.forEach((row, rowIndex) => {
    if (y > 270) {
      addFooter(doc, pages, 0); // temp, we'll fix total later
      doc.addPage();
      pages++;
      addHeader(doc, data.title);
      y = 36;

      // Re-draw header row
      doc.setFillColor(38, 38, 38);
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      x = 14;
      data.headers.forEach((header, i) => {
        doc.rect(x, y, colWidths[i], 10, "F");
        doc.text(header, x + cellPadding, y + 7);
        x += colWidths[i];
      });
      y += 10;
      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
    }

    x = 14;
    const bgColor = rowIndex % 2 === 0 ? 250 : 240;
    doc.setFillColor(bgColor, bgColor, bgColor);

    row.forEach((cell, i) => {
      doc.rect(x, y, colWidths[i], 8, "F");
      const maxChars = Math.floor(colWidths[i] / 2);
      doc.text(String(cell).slice(0, maxChars), x + cellPadding, y + 5);
      x += colWidths[i];
    });
    y += 8;
  });

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  doc.save(`${data.title.replace(/\s+/g, "_")}.pdf`);
}

export function exportToExcel(data: ReportData): void {
  const worksheetData = [data.headers, ...data.rows];
  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths
  const colWidths = data.headers.map((h) => ({ wch: Math.max(h.length + 2, 12) }));
  worksheet["!cols"] = colWidths;

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Report");

  XLSX.writeFile(workbook, `${data.title.replace(/\s+/g, "_")}.xlsx`);
}
