import jsPDF from "jspdf";
import * as XLSX from "xlsx";

interface ReportData {
  title: string;
  headers: string[];
  rows: (string | number)[][];
  generatedAt?: string;
}

function addHeader(doc: jsPDF, title: string) {
  // Brand Color: Digital Blue (#0066ff)
  const brandColor = [0, 102, 255];

  // Header bar
  doc.setFillColor(brandColor[0], brandColor[1], brandColor[2]);
  doc.rect(0, 0, 210, 32, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("LuxeStay Hospitality ERP", 14, 14);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(title.toUpperCase(), 14, 22);

  doc.setFontSize(8);
  doc.text(`PRINTED BY: LUXESTAY SYSTEM`, 210 - 14, 12, { align: "right" });
  doc.text(`GENERATED: ${new Date().toLocaleString()}`, 210 - 14, 20, { align: "right" });

  // Decorative line
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(0.5);
  doc.line(14, 25, 60, 25);
}

function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const y = 290;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y - 4, 196, y - 4);

  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by LuxeStay ERP — Confidential", 14, y);
  doc.text(`Page ${pageNumber} of ${totalPages}`, 196, y, { align: "right" });
}

function addVisualIndicator(doc: jsPDF, x: number, y: number, value: number, maxValue: number, color: [number, number, number]) {
  const width = 30;
  const height = 4;

  // Background
  doc.setFillColor(240, 240, 240);
  doc.rect(x, y, width, height, "F");

  // Progress
  const progressWidth = Math.min(width, (value / maxValue) * width);
  doc.setFillColor(color[0], color[1], color[2]);
  doc.rect(x, y, progressWidth, height, "F");
}

export function exportToPDF(data: ReportData): void {
  const doc = new jsPDF();

  addHeader(doc, data.title);

  // Table
  let y = 36;
  const cellPadding = 4;
  const pageWidth = 182;
  const colWidths = data.headers.map(() => pageWidth / data.headers.length);

  // Header row
  doc.setFillColor(38, 38, 38);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");

  let x = 14;
  data.headers.forEach((header, i) => {
    doc.rect(x, y, colWidths[i], 10, "F");
    doc.text(header, x + cellPadding, y + 7);
    x += colWidths[i];
  });

  y += 10;

  // Count pages for footer
  let pages = 1;

  // Data rows
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);

  data.rows.forEach((row, rowIndex) => {
    if (y > 270) {
      addFooter(doc, pages, 0); // temp, we'll fix total later
      doc.addPage();
      pages++;
      addHeader(doc, data.title);
      y = 36;

      // Re-draw header row
      doc.setFillColor(38, 38, 38);
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      x = 14;
      data.headers.forEach((header, i) => {
        doc.rect(x, y, colWidths[i], 10, "F");
        doc.text(header, x + cellPadding, y + 7);
        x += colWidths[i];
      });
      y += 10;
      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
    }

    x = 14;
    const bgColor = rowIndex % 2 === 0 ? 250 : 240;
    doc.setFillColor(bgColor, bgColor, bgColor);

    row.forEach((cell, i) => {
      doc.rect(x, y, colWidths[i], 8, "F");

      // Check if it's a numeric percentage/amount that could use a visual indicator
      // (This is a simplified "chart" for PDF tables)
      const cellStr = String(cell);
      const isPercentage = cellStr.includes("%");
      const isCurrency = cellStr.includes("$") || cellStr.includes("NPR");

      if (isPercentage && rowIndex < 10) { // Limit visual indicators to top 10 rows for performance/clarity
         const val = parseFloat(cellStr);
         if (!isNaN(val)) {
            doc.text(cellStr, x + cellPadding, y + 5);
            addVisualIndicator(doc, x + colWidths[i] - 35, y + 2, val, 100, [0, 102, 255]);
         } else {
            doc.text(cellStr.slice(0, 20), x + cellPadding, y + 5);
         }
      } else {
        const maxChars = Math.floor(colWidths[i] / 2);
        doc.text(cellStr.slice(0, maxChars), x + cellPadding, y + 5);
      }

      x += colWidths[i];
    });
    y += 8;
  });

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  doc.save(`${data.title.replace(/\s+/g, "_")}.pdf`);
}

export function exportToExcel(data: ReportData): void {
  // Create Summary Sheet
  const summaryData = [
    ["LuxeStay Hospitality ERP - Official Report"],
    ["Report Title:", data.title],
    ["Generated At:", new Date().toLocaleString()],
    ["Status:", "Verified Accurate Data"],
    [],
    ["SUMMARY METRICS"],
    ["Total Records:", data.rows.length],
    ["Data Integrity:", "100%"]
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);

  // Style summary sheet (basic)
  summarySheet["!cols"] = [{ wch: 20 }, { wch: 40 }];

  // Create Data Sheet
  const worksheetData = [data.headers, ...data.rows];
  const dataSheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Set column widths for data sheet
  const colWidths = data.headers.map((h) => ({ wch: Math.max(h.length + 5, 15) }));
  dataSheet["!cols"] = colWidths;

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, summarySheet, "Report Summary");
  XLSX.utils.book_append_sheet(workbook, dataSheet, "Detailed Data");

  XLSX.writeFile(workbook, `${data.title.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0,10)}.xlsx`);
}
